# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  default:
    external:
      name: xkeycloak_net

services:

  explorerdb.xkeycloak.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.xkeycloak.com
    hostname: explorerdb.xkeycloak.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  explorer.xkeycloak.com:
    image: hyperledger/explorer:latest
    container_name: explorer.xkeycloak.com
    hostname: explorer.xkeycloak.com
    environment:
      - DATABASE_HOST=explorerdb.xkeycloak.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./crypto:/tmp/crypto
      - walletstore:/opt/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.xkeycloak.com:
        condition: service_healthy

